name: Fast-Forward Merge from master to release

on:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Source branch (for dev environment)'
        required: true
        default: 'master'
      target_branch:
        description: 'Target branch (for prod environment)'
        required: true
        default: 'release'

jobs:
  ff-merge:
    name: Fast-Forward Merge for Prod Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Target Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.target_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Fetch Source Branch
        run: git fetch origin ${{ github.event.inputs.source_branch }}

      - name: Fast-Forward Merge
        run: git merge --ff-only origin/${{ github.event.inputs.source_branch }}

      - name: Push Changes
        run: git push origin ${{ github.event.inputs.target_branch }}
